import { theme } from 'antd';

const FONT = "'Inter', 'Roboto', 'Segoe UI', sans-serif";

// ── Vibrant Design Tokens ────────────────────────────────────────────────────
export const PALETTE = {
  indigo:  '#6366f1',
  violet:  '#8b5cf6',
  cyan:    '#06b6d4',
  emerald: '#10b981',
  rose:    '#f43f5e',
  amber:   '#f59e0b',
  pink:    '#ec4899',
  orange:  '#f97316',
};

export const darkTheme = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary:           '#6366f1',
    colorPrimaryHover:      '#818cf8',
    colorPrimaryActive:     '#4f46e5',
    colorBgBase:            '#070c14',
    colorBgContainer:       '#0d1628',
    colorBgElevated:        '#162236',
    colorBgLayout:          '#070c14',
    colorBgSpotlight:       '#1e2d4a',
    colorBorder:            'rgba(99,102,241,0.18)',
    colorBorderSecondary:   'rgba(99,102,241,0.09)',
    colorText:              '#e2e8f0',
    colorTextSecondary:     '#94a3b8',
    colorTextTertiary:      '#64748b',
    colorSuccess:           '#10b981',
    colorWarning:           '#f59e0b',
    colorError:             '#f43f5e',
    colorInfo:              '#06b6d4',
    borderRadius:            10,
    borderRadiusLG:          16,
    borderRadiusSM:          6,
    borderRadiusXS:          4,
    fontFamily:              FONT,
    fontSize:                13,
    fontSizeLG:              15,
    fontSizeXL:              18,
    fontWeightStrong:        700,
    lineHeight:              1.65,
    boxShadow:              '0 8px 40px rgba(0,0,0,0.55), 0 2px 8px rgba(99,102,241,0.2)',
    boxShadowSecondary:     '0 4px 20px rgba(0,0,0,0.3)',
    controlHeight:           36,
    controlHeightLG:         42,
    controlHeightSM:         28,
    motionDurationMid:       '0.25s',
    motionDurationSlow:      '0.35s',
  },
  components: {
    Layout: {
      siderBg:  '#060a18',
      headerBg: 'rgba(7,12,20,0.88)',
      bodyBg:   '#070c14',
    },
    Menu: {
      darkItemBg:            'transparent',
      darkSubMenuItemBg:     'rgba(99,102,241,0.04)',
      darkItemSelectedBg:    'rgba(99,102,241,0.14)',
      darkItemSelectedColor: '#a5b4fc',
      darkItemHoverBg:       'rgba(99,102,241,0.08)',
      itemHeight:             40,
      fontSize:               13,
      fontFamily:             FONT,
    },
    Card: {
      colorBgContainer:    '#0d1628',
      colorBorderSecondary:'rgba(99,102,241,0.12)',
      borderRadiusLG:       16,
      paddingLG:            20,
      fontFamily:           FONT,
      boxShadowTertiary:   '0 4px 20px rgba(0,0,0,0.3)',
    },
    Table: {
      colorBgContainer: '#0d1628',
      headerBg:         '#0a1120',
      borderColor:      'rgba(99,102,241,0.08)',
      rowHoverBg:       'rgba(99,102,241,0.07)',
      headerColor:      '#64748b',
      headerSplitColor: 'rgba(99,102,241,0.06)',
      fontFamily:       FONT,
      fontSize:         13,
    },
    Button: {
      fontFamily:    FONT,
      fontWeight:    600,
      borderRadius:  10,
      controlHeight: 36,
    },
    Input: {
      colorBgContainer:         'rgba(99,102,241,0.06)',
      colorBorder:              'rgba(99,102,241,0.2)',
      colorBgContainerDisabled: 'rgba(99,102,241,0.03)',
      fontFamily:               FONT,
      borderRadius:             10,
      controlHeight:            36,
      activeShadow:             '0 0 0 3px rgba(99,102,241,0.2)',
    },
    Select: {
      colorBgContainer: 'rgba(99,102,241,0.06)',
      colorBorder:      'rgba(99,102,241,0.2)',
      fontFamily:       FONT,
      borderRadius:     10,
    },
    DatePicker: {
      colorBgContainer: 'rgba(99,102,241,0.06)',
      colorBorder:      'rgba(99,102,241,0.2)',
      borderRadius:     10,
      fontFamily:       FONT,
    },
    Modal: {
      colorBgElevated: '#0d1628',
      fontFamily:      FONT,
      borderRadiusLG:  16,
    },
    Popover: {
      colorBgElevated: '#0d1628',
      fontFamily:      FONT,
    },
    Drawer: {
      colorBgElevated: '#0d1628',
      fontFamily:      FONT,
    },
    Tag: {
      borderRadius: 6,
      fontFamily:   FONT,
      fontSize:     12,
      fontSizeSM:   11,
    },
    Badge: {
      fontFamily: FONT,
    },
    Typography: {
      fontFamily: FONT,
    },
    Tabs: {
      fontFamily:   FONT,
      fontSize:     13,
      inkBarColor:  '#6366f1',
    },
    Form: {
      fontFamily:    FONT,
      labelFontSize: 13,
    },
    Checkbox: {
      borderRadius:  4,
      colorPrimary:  '#6366f1',
    },
    Statistic: {
      fontFamily:      FONT,
      titleFontSize:   11,
      contentFontSize: 28,
    },
    Timeline: { fontFamily: FONT },
    Progress: { colorSuccess: '#10b981' },
    Segmented: {
      colorBgLayout: 'rgba(99,102,241,0.1)',
      fontFamily:    FONT,
    },
    Tooltip: {
      colorBgSpotlight: '#1e2d4a',
    },
  },
};

export const lightTheme = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary:        '#6366f1',
    colorPrimaryHover:   '#818cf8',
    colorPrimaryActive:  '#4f46e5',
    colorBgBase:         '#f8faff',
    colorBgContainer:    '#ffffff',
    colorBgLayout:       '#eef1ff',
    colorBgElevated:     '#ffffff',
    colorBorder:         'rgba(99,102,241,0.18)',
    colorBorderSecondary:'rgba(99,102,241,0.1)',
    colorText:           '#1e293b',
    colorTextSecondary:  '#475569',
    colorTextTertiary:   '#94a3b8',
    colorSuccess:        '#10b981',
    colorWarning:        '#f59e0b',
    colorError:          '#f43f5e',
    colorInfo:           '#06b6d4',
    borderRadius:         10,
    borderRadiusLG:       16,
    borderRadiusSM:       6,
    fontFamily:           FONT,
    fontSize:             13,
    fontSizeLG:           15,
    fontWeightStrong:     700,
    lineHeight:           1.65,
    controlHeight:        36,
    controlHeightLG:      42,
    controlHeightSM:      28,
    boxShadow:           '0 4px 24px rgba(99,102,241,0.1), 0 1px 3px rgba(0,0,0,0.06)',
  },
  components: {
    Layout: {
      siderBg:  '#060a18',
      headerBg: 'rgba(248,250,255,0.88)',
      bodyBg:   '#eef1ff',
    },
    Menu: {
      itemBg:            'transparent',
      subMenuItemBg:     'rgba(99,102,241,0.04)',
      itemSelectedBg:    'rgba(99,102,241,0.12)',
      itemSelectedColor: '#6366f1',
      itemHoverBg:       'rgba(99,102,241,0.06)',
      itemHeight:         40,
      fontSize:           13,
      fontFamily:         FONT,
    },
    Card: {
      borderRadiusLG:       16,
      paddingLG:            20,
      fontFamily:           FONT,
      colorBorderSecondary: 'rgba(99,102,241,0.1)',
    },
    Table: {
      headerBg:    'rgba(99,102,241,0.04)',
      borderColor: 'rgba(99,102,241,0.08)',
      rowHoverBg:  'rgba(99,102,241,0.04)',
      fontFamily:  FONT,
      fontSize:    13,
    },
    Button: {
      fontFamily:    FONT,
      fontWeight:    600,
      borderRadius:  10,
      controlHeight: 36,
    },
    Input: {
      fontFamily:    FONT,
      borderRadius:  10,
      controlHeight: 36,
      activeShadow:  '0 0 0 3px rgba(99,102,241,0.15)',
    },
    Select: {
      fontFamily:   FONT,
      borderRadius: 10,
    },
    DatePicker: {
      borderRadius: 10,
      fontFamily:   FONT,
    },
    Modal: {
      borderRadiusLG: 16,
      fontFamily:     FONT,
    },
    Drawer: { fontFamily: FONT },
    Tag: {
      borderRadius: 6,
      fontFamily:   FONT,
      fontSize:     12,
    },
    Statistic: {
      fontFamily:      FONT,
      titleFontSize:   11,
      contentFontSize: 28,
    },
    Typography: { fontFamily: FONT },
    Form: {
      fontFamily:    FONT,
      labelFontSize: 13,
    },
    Checkbox: { colorPrimary: '#6366f1' },
    Segmented: { fontFamily: FONT },
    Tabs: {
      fontFamily:  FONT,
      fontSize:    13,
      inkBarColor: '#6366f1',
    },
    Timeline: { fontFamily: FONT },
  },
};
